### ISSUE TITLE
Training datasets can not be downloaded

### ISSUE THREAD

**Issue by Songshilongi** [CYF2000127/MolNexTR#4]
Training datasets can not be downloaded， can you share a new link ?

**Comment by CYF2000127** [comment]
Thanks for your feedback. We will soon create a new link for the datasets

**Comment by Songshilongi** [comment]
could you tell me what's the difference between MolNexTR and MolScribe?

**Comment by Songshilongi** [comment]
Are the training data and augmentation methods different, or are the same data used but with different augmentation methods?

**Comment by CYF2000127** [comment]
We implemented more advanced data augmentation algorithms and refined post-processing techniques for improved results.

**Comment by CYF2000127** [comment]
We also use the different encoders; only decoder remains the same.
